### ISSUE TITLE
Documentation: Alpine support for MacOS M1 with Visual Studio Code

### ISSUE THREAD

**Issue by gavin-shaw** [qdm12/reactdevcontainer#4]
Thanks for the amazing work.

Maybe consider adding a warning about using this container out of the box on Mac M1. Vscode has this outstanding issue:

https://github.com/microsoft/vscode-remote-release/issues/4462

"Alpine Linux is not supported on the hardware architecture 'aarch64' of the container".

To work around I modified the `qmcgaw/reactdevcontainer` Dockerfile in the root dir to use debian:

(change base image and switch from apk to apt)

```Dockerfile
FROM qmcgaw/basedevcontainer:debian
ARG CREATED
ARG COMMIT
ARG VERSION=local
LABEL \
    org.opencontainers.image.authors="quentin.mcgaw@gmail.com" \
    org.opencontainers.image.created=$CREATED \
    org.opencontainers.image.version=$VERSION \
    org.opencontainers.image.revision=$COMMIT \
    org.opencontainers.image.url="https://github.com/qdm12/reactdevcontainer" \
    org.opencontainers.image.documentation="https://github.com/qdm12/reactdevcontainer" \
    org.opencontainers.image.source="https://github.com/qdm12/reactdevcontainer" \
    org.opencontainers.image.title="React Dev container Alpine" \
    org.opencontainers.image.description="React TS development container for Visual Studio Code Remote Containers development"
# Install Debian packages
ENV DEBIAN_FRONTEND noninteractive
RUN apt update && \
    apt install -y nodejs npm
RUN npm cache clean -f
RUN npm install -g n
RUN n stable
RUN npm install -g yarn
# Setup shells
COPY shell/.zshrc-specific shell/.welcome.sh /root/
# Sets directories for NPM global packages
ENV NODE_PATH="/root/.npm-packages/lib/node_modules" \
    MANPATH="/root/.npm-packages/share/man"
RUN echo "prefix = /root/.npm-packages" >> /root/.npmrc && \
    chmod 600 /root/.npmrc
ENV PATH=/root/.npm-packages/bin:$PATH
# Fix ownership and permissions of anonymous volume 'node_modules'
VOLUME [ "/workspace/node_modules" ]
RUN mkdir -p /workspace/node_modules && \
    chmod 700 /workspace/node_modules

```
And rebuilt it locally:

```
docker build -t qmcgaw/reactdevcontainer .
```

Please do let me know if there is a better workaround for now.

**Comment by qdm12** [comment]
Hey there! Assuming the [modified CI](https://github.com/qdm12/reactdevcontainer/actions/runs/1246210907) builds correctly, you should soon have a `qmcgaw/reactdevcontainer:debian` image as well 😉  I also pinned it to `qmcgaw/basedevcontainer:v0.3.0-debian` to limit surprises.

I updated the readme as well to highlight the alpine doesn't work on `arm64`, although this should change soon in the coming days seeing the discussion on the issue you linked.

If you find anything broken or annoying, feel free to create a new issue! Thanks!
